use std::time::Duration;

use reqwest::StatusCode;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::ollama::{
    Client, KeepAlive, OllamaError, Role,
    enums::{ModelOptions, Think},
};

#[derive(Debug, Clone, Serialize)]
pub struct Message {
    /// Role of the message within the conversation.
    pub role: Role,

    /// Text content of the message.
    pub content: String,
}

#[derive(Debug, Serialize)]
struct ChatRequest {
    /// The name of the model to request the chat from.
    pub model: String,

    /// Chat history as an array of message objects (each with a role and content)
    pub messages: Vec<Message>,

    // TODO: add `tools: object[]` -- Optional list of function tools the model may call during the chat
    // TODO: add `format: enum<string> | object[]` -- Format to return a response in. Can be json or a JSON schema.
    /// Runtime options that control text generation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<ModelOptions>,

    /// Whether Ollama should stream partial responses as they are generated.
    stream: bool,

    /// When set, returns separate thinking output in addition to content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub think: Option<Think>,

    /// Format to return a response in. Can be `"json"` or a JSON schema.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<Value>,

    /// How long Ollama should keep the model loaded in memory after the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub keep_alive: Option<KeepAlive>,
}

/// Options controlling a chat request.
///
/// Defaults are chosen independently from Ollama's own defaults.
#[derive(Debug, Clone)]
pub struct ChatOptions {
    /// Runtime options controlling model inference.
    pub options: Option<ModelOptions>,

    /// Whether and how to enable model thinking.
    pub think: Option<Think>,

    /// Requested response format.
    ///
    /// This may be `"json"` or a JSON Schema describing the desired structured output.
    pub format: Option<Value>,

    /// How long Ollama should keep the model loaded in memory after the request.
    ///
    /// If omitted, Ollama uses its configured default.
    pub keep_alive: Option<KeepAlive>,

    /// Maximum duration allowed for the HTTP request.
    pub timeout: Option<Duration>,
}

impl Default for ChatOptions {
    fn default() -> Self {
        Self {
            options: Some(ModelOptions::default()),
            think: Some(false.into()),
            format: None,
            keep_alive: None,
            timeout: Some(Duration::from_mins(1)),
        }
    }
}

/// Completed response from an Ollama chat request.
#[derive(Debug, Deserialize)]
pub struct ChatResponse {
    /// Model that generated the response.
    pub model: String,

    /// Message generated by the assistant.
    pub message: ResponseMessage,

    /// Indicates whether the chat response has finished.
    pub done: bool,

    /// Reason the response finished, if reported by Ollama.
    pub done_reason: Option<String>,

    /// Total number of prompt tokens processed.
    pub prompt_eval_count: Option<u64>,

    /// Number of output tokens generated.
    pub eval_count: Option<u64>,
}

/// Message generated by the assistant.
#[derive(Debug, Deserialize)]
pub struct ResponseMessage {
    /// Assistant message text.
    pub content: String,

    /// Optional deliberate thinking trace when think is enabled.
    #[serde(default)]
    pub thinking: Option<String>,
    // TODO: add `tool_calls: object[]` -- Tool calls requested by the assistant.
    // TODO: add `images: string[]` -- Optional list of inline images for multimodal models. (Base64-encoded image content.)
}

impl Client {
    /// Generate the next assistant message for a conversation.
    ///
    /// `model` specifies the Ollama model to use, `messages` contains the conversation history,
    /// and `options` controls inference and request behavior.
    ///
    /// If Ollama returns a `404`, the available models are queried to distinguish a missing model
    /// from other not-found errors.
    pub fn chat(
        &self,
        model: impl Into<String>,
        messages: Vec<Message>,
        options: &ChatOptions,
    ) -> Result<ChatResponse, OllamaError> {
        let request = ChatRequest {
            model: model.into(),
            messages,
            options: options.options.clone(),
            stream: false,
            think: options.think,
            format: options.format.clone(),
            keep_alive: options.keep_alive,
        };

        let mut response = self
            .client
            .post(format!("{}/api/chat", self.base_url))
            .json(&request);

        if let Some(timeout) = options.timeout {
            response = response.timeout(timeout);
        }

        match self.call(response) {
            Err(
                error @ OllamaError::Api {
                    status: StatusCode::NOT_FOUND,
                    ..
                },
            ) => Err(self.resolve_model_not_found(&request.model, error)),

            result => result,
        }
    }
}
