use std::{
    io::{BufRead, BufReader},
    num::NonZeroU64,
    time::Duration,
};

use reqwest::StatusCode;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::ollama::{
    Client, KeepAlive, OllamaError, Role,
    enums::{ModelOptions, Think},
};

#[derive(Debug, Clone, Serialize)]
pub struct Message {
    /// Role of the message within the conversation.
    pub role: Role,

    /// Text content of the message.
    pub content: String,
}

#[derive(Debug, Serialize)]
struct ChatRequest {
    /// The name of the model to request the chat from.
    pub model: String,

    /// Chat history as an array of message objects (each with a role and content)
    pub messages: Vec<Message>,

    // TODO: add `tools: object[]` -- Optional list of function tools the model may call during the chat
    /// Runtime options that control text generation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<ModelOptions>,

    /// Whether Ollama should stream partial responses as they are generated.
    stream: bool,

    /// When set, returns separate thinking output in addition to content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub think: Option<Think>,

    /// Format to return a response in. Can be `"json"` or a JSON schema.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<Value>,

    /// How long Ollama should keep the model loaded in memory after the request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub keep_alive: Option<KeepAlive>,
}

impl ChatRequest {
    pub fn new(
        model: impl Into<String>,
        messages: Vec<Message>,
        options: &ChatOptions,
        stream: bool,
    ) -> Self {
        Self {
            model: model.into(),
            messages,
            options: options.options.clone(),
            stream,
            think: options.think,
            format: options.format.clone(),
            keep_alive: options.keep_alive,
        }
    }
}

/// Options controlling a chat request.
///
/// Defaults are chosen independently from Ollama's own defaults.
#[derive(Debug, Clone)]
pub struct ChatOptions {
    /// Runtime options controlling model inference.
    pub options: Option<ModelOptions>,

    /// Whether and how to enable model thinking.
    pub think: Option<Think>,

    /// Requested response format.
    ///
    /// This may be `"json"` or a JSON Schema describing the desired structured output.
    pub format: Option<Value>,

    /// How long Ollama should keep the model loaded in memory after the request.
    ///
    /// If omitted, Ollama uses its configured default.
    pub keep_alive: Option<KeepAlive>,

    /// Maximum duration allowed for the HTTP request.
    pub timeout: Option<Duration>,
}

impl Default for ChatOptions {
    fn default() -> Self {
        Self {
            options: Some(ModelOptions::default()),
            think: Some(false.into()),
            format: None,
            keep_alive: None,
            timeout: Some(Duration::from_mins(2)),
        }
    }
}

/// Completed response from an Ollama chat request.
#[derive(Debug, Deserialize)]
pub struct ChatResponse {
    /// Model that generated the response.
    pub model: String,

    /// Message generated by the assistant.
    pub message: ResponseMessage,

    /// Indicates whether the chat response has finished.
    pub done: bool,

    /// Reason the response finished, if reported by Ollama.
    pub done_reason: Option<String>,

    /// Total number of prompt tokens processed.
    pub prompt_eval_count: Option<u64>,

    /// Number of output tokens generated.
    pub eval_count: Option<u64>,
}

/// A meaningful transition observed while a chat response is being streamed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ChatEvent {
    /// A streamed fragment of deliberate reasoning output.
    Thinking(String),
    /// A streamed fragment of visible response content.
    Generating(String),
}

/// Message generated by the assistant.
#[derive(Debug, Deserialize)]
pub struct ResponseMessage {
    /// Assistant message text.
    pub content: String,

    /// Optional deliberate thinking trace when think is enabled.
    #[serde(default)]
    pub thinking: Option<String>,
    // TODO: add `tool_calls: object[]` -- Tool calls requested by the assistant.
}

impl Client {
    /// Load the model using the same runner options as a subsequent chat request.
    /// Returned is the "done reason".
    ///
    /// An empty message list instructs Ollama to prepare a runner without generating text.
    pub fn prepare_model(
        &self,
        model: impl Into<String>,
        options: &ChatOptions,
    ) -> Result<Option<String>, OllamaError> {
        let mut preparation_options = options.clone();
        preparation_options.think = None;
        preparation_options.format = None;
        // TODO: find a better way to preload the model than with 1m keep alive!
        preparation_options.keep_alive = match options.keep_alive {
            Some(KeepAlive::UnloadImmediately) => Some(KeepAlive::minutes(NonZeroU64::MIN)),
            keep_alive => keep_alive,
        };

        self.chat(model, Vec::new(), &preparation_options)
            .map(|resp| resp.done_reason)
    }

    /// Generate the next assistant message for a conversation.
    ///
    /// `model` specifies the Ollama model to use, `messages` contains the conversation history,
    /// and `options` controls inference and request behavior.
    ///
    /// If Ollama returns a `404`, the available models are queried to distinguish a missing model
    /// from other not-found errors.
    pub fn chat(
        &self,
        model: impl Into<String>,
        messages: Vec<Message>,
        options: &ChatOptions,
    ) -> Result<ChatResponse, OllamaError> {
        let request = ChatRequest::new(model, messages, options, false);
        let response = self.send_chat(&request, options.timeout)?;
        let body = response.bytes()?;
        Ok(serde_json::from_slice(&body)?)
    }

    /// Generate a chat response while reporting when Ollama starts thinking and producing content.
    ///
    /// Response fragments are accumulated internally so callers retain the same completed response
    /// representation used by non-streaming requests.
    pub fn chat_stream<F>(
        &self,
        model: impl Into<String>,
        messages: Vec<Message>,
        options: &ChatOptions,
        on_event: F,
    ) -> Result<ChatResponse, OllamaError>
    where
        F: FnMut(ChatEvent),
    {
        let request = ChatRequest::new(model, messages, options, true);
        let response = self.send_chat(&request, options.timeout)?;

        collect_stream(BufReader::new(response), on_event)
    }

    /// Send a chat request, enriching a missing-model response when possible.
    fn send_chat(
        &self,
        request: &ChatRequest,
        timeout: Option<Duration>,
    ) -> Result<reqwest::blocking::Response, OllamaError> {
        let mut response = self
            .client
            .post(format!("{}/api/chat", self.base_url))
            .json(request);
        if let Some(timeout) = timeout {
            response = response.timeout(timeout);
        }

        match Self::send(response) {
            Err(
                error @ OllamaError::Api {
                    status: StatusCode::NOT_FOUND,
                    ..
                },
            ) => Err(self.resolve_model_not_found(&request.model, error)),
            result => result,
        }
    }
}

fn collect_stream<R, F>(reader: R, mut on_event: F) -> Result<ChatResponse, OllamaError>
where
    R: BufRead,
    F: FnMut(ChatEvent),
{
    let mut content = String::new();
    let mut thinking = String::new();
    let mut final_response = None;

    for line in reader.lines() {
        let line = line?;
        if line.trim().is_empty() {
            continue;
        }
        let chunk: ChatResponse = serde_json::from_str(&line)?;

        if let Some(delta) = chunk.message.thinking.as_deref()
            && !delta.is_empty()
        {
            on_event(ChatEvent::Thinking(delta.to_owned()));
            thinking.push_str(delta);
        }
        if !chunk.message.content.is_empty() {
            on_event(ChatEvent::Generating(chunk.message.content.clone()));
            content.push_str(&chunk.message.content);
        }

        if chunk.done {
            final_response = Some(chunk);
            break;
        }
    }

    // TODO: double-check that all fields are correctly field (esp. `eval_count`)!
    let final_response = final_response.ok_or(OllamaError::IncompleteStream)?;
    Ok(ChatResponse {
        model: final_response.model,
        message: ResponseMessage {
            content,
            thinking: (!thinking.is_empty()).then_some(thinking),
        },
        done: true,
        done_reason: final_response.done_reason,
        prompt_eval_count: final_response.prompt_eval_count,
        eval_count: final_response.eval_count,
    })
}

#[cfg(test)]
mod tests {
    use std::io::Cursor;

    use super::*;

    #[test]
    fn streamed_response_is_accumulated_and_reports_phase_transitions() {
        let stream = concat!(
            r#"{"model":"test","message":{"content":"","thinking":"reason"},"done":false}"#,
            "\n",
            r#"{"model":"test","message":{"content":"","thinking":"ing"},"done":false}"#,
            "\n",
            r#"{"model":"test","message":{"content":"subject","thinking":""},"done":false}"#,
            "\n",
            r#"{"model":"test","message":{"content":"","thinking":""},"done":true,"done_reason":"stop","prompt_eval_count":12,"eval_count":3}"#,
            "\n",
        );
        let mut events = Vec::new();

        let response = collect_stream(Cursor::new(stream), |event| events.push(event)).unwrap();

        assert_eq!(
            events,
            [
                ChatEvent::Thinking("reason".to_owned()),
                ChatEvent::Thinking("ing".to_owned()),
                ChatEvent::Generating("subject".to_owned()),
            ]
        );
        assert_eq!(response.message.thinking.as_deref(), Some("reasoning"));
        assert_eq!(response.message.content, "subject");
        assert_eq!(response.prompt_eval_count, Some(12));
        assert_eq!(response.eval_count, Some(3));
    }
}
