use std::{num::NonZeroU64, time::Duration};

use serde::Serialize;

/// Role of a message in an Ollama chat conversation.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// Instructions that define the assistant's behavior or context.
    System,

    /// A message supplied by the user.
    User,

    /// A previous response generated by the assistant.
    Assistant,
}

/// Runtime options controlling model inference.
///
/// Fields left as `None` are omitted from the request, allowing Ollama or the selected model to use
/// its configured default.
///
/// Defaults are chosen independently from Ollama's own defaults.
#[derive(Debug, Clone, Serialize)]
pub struct ModelOptions {
    /// Random seed used for deterministic generation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,

    /// Sampling temperature controlling output randomness.
    ///
    /// Lower values generally make output more deterministic.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// Maximum context window size, in tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_ctx: Option<u32>,

    /// Maximum number of tokens to generate.
    ///
    /// Ollama also accepts negative values with special meanings, so this field is signed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub num_predict: Option<i32>,
}

/// Controls whether and how a model exposes its reasoning output.
///
/// Ollama accepts either a boolean or, for models supporting configurable reasoning effort, a [`ThinkLevel`].
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(untagged)]
pub enum Think {
    /// Enable or disable thinking.
    Enabled(bool),

    /// Request a particular reasoning effort.
    Level(ThinkLevel),
}

/// Requested reasoning effort for models that support configurable thinking.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum ThinkLevel {
    /// Low reasoning effort.
    Low,

    /// Medium reasoning effort.
    Medium,

    /// High reasoning effort.
    High,

    /// Maximum reasoning effort.
    Max,
}

/// Controls how long Ollama keeps a model loaded in memory after a request.
#[derive(Debug, Clone, Copy)]
pub enum KeepAlive {
    /// Keep the model loaded for the given positive number of seconds.
    ForSeconds(NonZeroU64),

    /// Unload the model immediately after the request completes.
    UnloadImmediately,

    /// Keep the model loaded indefinitely.
    Indefinitely,
}

impl KeepAlive {
    /// Keep the model loaded for the given positive number of seconds.
    pub fn seconds(seconds: NonZeroU64) -> Self {
        Self::ForSeconds(seconds)
    }

    /// Keep the model loaded for the given positive number of minutes.
    ///
    /// # Panics
    ///
    /// Panics if converting the duration to seconds would overflow a [`u64`].
    pub fn minutes(minutes: NonZeroU64) -> Self {
        const SECONDS_PER_MINUTE: NonZeroU64 = NonZeroU64::new(60).expect("60 is non-zero");

        Self::ForSeconds(
            minutes
                .checked_mul(SECONDS_PER_MINUTE)
                .expect("keep-alive duration overflow"),
        )
    }
}

impl Serialize for KeepAlive {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Self::ForSeconds(seconds) => serializer.serialize_u64(seconds.get()),
            Self::UnloadImmediately => serializer.serialize_u64(0),
            Self::Indefinitely => serializer.serialize_i64(-1),
        }
    }
}

impl Default for ModelOptions {
    fn default() -> Self {
        ModelOptions {
            seed: None,
            temperature: Some(0.0),
            num_ctx: Some(16_384),
            num_predict: None,
        }
    }
}

impl Default for Think {
    fn default() -> Self {
        Self::Enabled(false)
    }
}

impl From<bool> for Think {
    fn from(value: bool) -> Self {
        Self::Enabled(value)
    }
}

impl From<ThinkLevel> for Think {
    fn from(level: ThinkLevel) -> Self {
        Self::Level(level)
    }
}

impl From<Duration> for KeepAlive {
    fn from(duration: Duration) -> Self {
        if duration.is_zero() {
            return Self::UnloadImmediately;
        }

        let seconds = duration
            .as_secs()
            .saturating_add(u64::from(duration.subsec_nanos() != 0));
        match NonZeroU64::try_from(seconds) {
            Ok(seconds) => Self::ForSeconds(seconds),
            Err(_) => Self::UnloadImmediately, // should actually never happen
        }
    }
}
